### ISSUE TITLE
Performance issues with large icons sets

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/icons#3] opened 2020-11-18 09:48 UTC
PR #2 adds two sets of 200+ icons each. Since every icon currently corresponds to an HTTP request, the loading of these sets results in a bit of a perf issue and long loading times.

Maybe consider downloading the icons to the user's pc in the notion-enhancer installation folder and serve them from disk rather than directly from Github? The only downside of this is that the icon pack could change on the repo and not be updated on the user's side. Maybe refreshing it every once in a while (e.g. at start of notion-enhancer) could be a solution to this.

Another solution to this issue could be using a CSS sprite to load the icons, resulting in a single (even though larger) HTTP request. The downside to this is that this is a new "feature" that should be developed.

Let me think what you think.

**Comment by dragonwocky** [comment] 2020-11-18 10:13
Considering Notion doesn't work offline anyway and 200+ is a lot of files to download, a spritesheet seems the most ideal, though it does raise questions with how the icon is then used (because I'm guessing it works by Notion's "link" icon input).

Perhaps it might be a good idea to make the repo icon sets toggleable so if users don't want to load every icon they don't have to?

@CloudHill what do you think?

**Comment by fabiosangregorio** [comment] 2020-11-18 10:18
Well, notion _does_ work offline. Making the sets toggleable could be used to download the icon set to the user's disk in order to be cached and used offline as well.

On the sprite way, instead, icon sets could be loaded via a sprite in the icons menu, and added via the repo URL when chosen as the page icon.

**Comment by dragonwocky** [comment] 2020-11-18 10:48
Oh, does it? I know you can open the app, but I was under the impression that only pages pre-loaded work and you can't do a lot with it. Besides, if the icons are added via the repo URL then an internet connection is necessary for the mod to work either way.

Sprite way does sound best, and then just re-caching the spritesheets every now and then.

**Comment by CloudHill** [comment] 2020-11-18 10:55
Toggleable icon sets is something I'm already planning on doing, but I thought that could wait till more icon sets are added. I wasn't expecting 200+ icon sets to be added so early on 😅. I've never worked with spritesheets before, but if it'll increase performance, I'll give it a go.

Also found out the icons were made by Finbah Neill: https://www.reddit.com/r/Notion/comments/jsezwz/who_made_the_minimal_notion_icons_page/

**Comment by fabiosangregorio** [comment] 2020-11-19 09:20
> I was under the impression that only pages pre-loaded work and you can't do a lot with it.

@dragonwocky I tested it today, and I can open and close notion, navigate the workspace and edit pages normally while offline.

@CloudHill I saw the PR was merged. Performance-wise now is really great! Loading the whole icon set takes less than a second :)
I'm experimenting visual issues though, as you can see here:

![](https://i.imgur.com/QrlRGeY.png)

Are you able to reproduce?

**Comment by fabiosangregorio** [comment] 2020-11-19 09:22
Also, before closing this issue: could you please write a mini-guide and link resources on how you create the sprites? I'm assuming that sprite creation will have to be updated on every icon change/new icon sets.

**Comment by CloudHill** [comment] 2020-11-19 11:09
No idea, it seems totally fine on my end.
![image](https://user-images.githubusercontent.com/54142180/99658569-42d85e00-2a92-11eb-97b8-a6743babfb35.png)
Does it only happen on that particular icon set?

**Comment by fabiosangregorio** [comment] 2020-11-19 11:12
All icon sets. 

I tested and the cause it's likely that I have a higher zoom level than the default :)

**Comment by CloudHill** [comment] 2020-11-19 11:17
Do you mean zooming using the `ctrl` `+` shortcut? I still can't reproduce it even when zooming in.

**Comment by fabiosangregorio** [comment] 2020-11-19 11:27
Yep, that's what I mean. Uhmmm that's strange, I'm running the latest dev build. I'm not sure what to do

**Comment by CloudHill** [comment] 2020-11-19 11:47
@dragonwocky do you have this issue as well? If you do, maybe you can help do some troubleshooting

**Comment by dragonwocky** [comment] 2020-11-19 12:04
...works fine for me 🤔

**Comment by CloudHill** [comment] 2020-11-19 12:07
@fabiosangregorio try checking if any styles are overriding the ones I've set. the icons itself should have a width and height of 32 pixels.

**Comment by fabiosangregorio** [comment] 2020-11-19 14:00
I tried:
* removing and reapplying the latest dev build of the enhancer
* remove all enhancements, and reactivate only notion icons
* removing all styles

I still encounter this issue with zoom levels higher than 100%. Hitting "ctrl -" two times reduces the zoom level back to 100% and fixes the problem.

Here you can see the DOM and the style in the DevTools

![](https://i.imgur.com/b2sWduI.png)

**Comment by CloudHill** [comment] 2020-11-20 11:29
Can you try removing the `padding: 4px` style?

**Comment by fabiosangregorio** [comment] 2020-11-20 15:10
Nope, nothing changes. :( I'm pretty sure it's because of the zoom level though.

**Comment by CloudHill** [comment] 2020-11-20 15:50
Can you try adding this style?
```css
.notion-icons--icon > div {
    background-size: 32px !important;
}
```

**Comment by fabiosangregorio** [comment] 2020-11-20 18:39
@CloudHill Hell yeah! That fixes it on all zoom levels, thank you very much. You can go ahead and close this.

**Comment by CloudHill** [comment] 2020-11-21 04:01
Nice, I made a pull request that should fix this permanently, so you should be able to remove the style afterwards.
I also don't have access to closing issues, so I'll let you close this.

**Closed as completed** 2020-11-21 06:19 UTC
